name: CI
on:
  push:
    branches:    
      - 'main'
      - 'next'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        node-version:
          - '16.x'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci --ignore-scripts
      - run: npm run lint
  test-unit:
    needs: lint
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest
        node-version:
          - '12.x'
          - '14.x'
          - '16.x'
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci --ignore-scripts
      - run: npm run build --if-present
      - run: npm run test:unit