name: Release patch
on:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        node-version:
          - '16.x'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Checkout next
        run: |
          git config --local user.email "release@github.com"
          git config --local user.name "Release"
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git checkout next
          git pull github next --ff-only
      - run: npm ci --ignore-scripts
      - run: npm run release:patch
      - run: npm run build --if-present
      - run: npm run test:unit
      - name: Commit files
        run: |
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          git commit -m "chore: Release"
          git push github HEAD:${GITHUB_REF}