name: Renovate
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      renovate-token:
        description: 'The token used for renovate bot'     
        required: true
        default: ${{ secrets.RENOVATE_TOKEN }}
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v29.27.0
        with:
          configurationFile: example/renovate-config.js
          token: ${{ github.event.inputs.renovate-token }}
